version: '2'
services:
  java:
    build: .
    ports:
     - "4567:4567"
    links:
     - redis
    depends_on:
      - redis
  redis:
    image: redis
    ports:
     - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
volumes:
  redis-data: {}